host: login.salesforce.com
client_secret: 5934656462821809054
client_id: 3MVG9xOCXq4ID1uFbdgU4Qdni_UqKd2sZLdz1hVcy4nLc.wVzfja5RjMQ4gY3XTCUIwxRHSrUKDlkLXTcD.9A
sobject_module: SFDC_Models
debugging: false
username: leisurely@berkeley.edu
password: pleasedontkillme1AHa7lYKA04CtRfaYdOgNdxMa